# No k8s needed
---
spring:
  config:
    activate:
      on-profile: postgres

  datasource:
    url: jdbc:postgresql://localhost:5432/camunda-db
    username: postgres
    password: password

  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  sql:
    init:
      platform: postgresql
#      schema-locations: classpath:sql/schema.sql
#      data-locations: classpath:sql/data.sql

logging.level:
  org.hibernate:
    SQL: DEBUG
    type.descriptor.sql.BasicBinder: TRACE


