version: "3"
services:

  postgres:
    container_name: postgres_camunda
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: camunda-db
      PGDATA: "/data/postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /var/lib/postgres
    #      - ./docker/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres-data:

